### ISSUE TITLE
Connection unexpectedly closed

### ISSUE THREAD

**Issue by Mohammad271091** [aydinnyunus/Keylogger#3]
Thanks for the great work.. 
but I get this error.. this is the last line of it:

raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

how can I solve this issue ?

**Comment by aydinnyunus** [comment]
Look this solutions : https://stackoverflow.com/questions/17759860/python-2-smtpserverdisconnected-connection-unexpectedly-closed

**Comment by bhimbolar** [comment]
I cannot see any main.py file in the source code. All there is, is the keylogger.py file. Is there an omission or the file has been deleted?

**Comment by aydinnyunus** [comment]
I fixed the READ.me it's my mistake.I refer keylogger.py

**Comment by aydinnyunus** [comment]
> I cannot see any main.py file in the source code. All there is, is the keylogger.py file. Is there an omission or the file has been deleted?

I fixed the READ.me it's my mistake.I refer keylogger.py

**Comment by bhimbolar** [comment]
Great! Thank you.

**Comment by bhimbolar** [comment]
One more issue please... I converted keylogger.py to exe and when i run the output exe file, i get an error: "Failed to execute script keylogger". Please kindly help with the solution to this. I have also tried using auto-py-to-exe but i still get the error.

**Comment by aydinnyunus** [comment]
> One more issue please... I converted keylogger.py to exe and when i run the output exe file, i get an error: "Failed to execute script keylogger". Please kindly help with the solution to this. I have also tried using auto-py-to-exe but i still get the error.

Try this solutions first one is working for me : https://stackoverflow.com/questions/41570359/how-can-i-convert-a-py-to-exe-for-python

**Comment by bhimbolar** [comment]
Thank you! It worked. I now receive logs but I do not receive screenshots or microphone audio. Please kindly advise on what to do. Thanks in anticipation!

**Comment by KaravaliStudio** [comment]
> Thank you! It worked. I now receive logs but I do not receive screenshots or microphone audio. Please kindly advise on what to do. Thanks in anticipation!

Please help me
